apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
 name: ocs-storagecluster
 namespace: openshift-storage
spec:
 manageNodes: false
 resources:
   mds:
     limits:
       cpu: "3"
       memory: "8Gi"
     requests:
       cpu: "3"
       memory: "8Gi"
 monDataDirHostPath: /var/lib/rook
 storageDeviceSets:
 - count: 1  
   dataPVCTemplate:
     spec:
       accessModes:
       - ReadWriteOnce
       resources:
         requests:
           storage: "100Gi" 
       storageClassName: localblock
       volumeMode: Block
   name: ocs-deviceset
   placement: {}
   portable: false
   replica: 3
   resources:
     limits:
       cpu: "2"
       memory: "5Gi"
     requests:
       cpu: "2"
       memory: "5Gi"
